### ISSUE TITLE
Do sample code, Error is occar 

### ISSUE THREAD

**Issue by Sueoka-ppc** [vanstorm9/AI-Vocaloid-Kit-V2#1]
When do sample code

python3 main.py --modelPath savedModels/9-22-music.pt --seed inputs/noteSeed.txt --dupThresh 3 --numOfNotes 50

```
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    train_data, test_data = torchtext.data.TabularDataset.splits(path='./', train='colab/pipeline/trainNotes.csv', validation='colab/pipeline/valNotes.csv', format='csv', fields=data_fields)
  File "/home/sueoka/anaconda3/envs/vocalo/lib/python3.6/site-packages/torchtext/data/dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "/home/sueoka/anaconda3/envs/vocalo/lib/python3.6/site-packages/torchtext/data/dataset.py", line 251, in __init__
    with io.open(os.path.expanduser(path), encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './colab/pipeline/trainNotes.csv'
```

What is wrong?

**Comment by vanstorm9** [comment]
Hello, I checked it out and this is due to an incorrect hard-coded file path location (of a file containing training data of extracted vsqx notes) within the script. I changed it so that the script would use the correct path location of trainNotes.csv. You should be able to run it now.
